services:
    sonata.admin.user:
        class: VTE\BackendVEGBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "User" }
        arguments:
            - ~
            - VTE\VEGBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [VTEBackendVEGBundle]]
